### PR TITLE
api and aws 上傳

### PR DESCRIPTION
**Pull request by robinsonlin603**
老師好 我是林厚安 discord是Robinson＼(￣▽￣)／#1551

1. http://35.153.147.80:3000/api/attracions?page=1

image

2. http://35.153.147.80:3000/api/attracions?page=0&keyword=%E8%97%9D%E8%A1%93

image

3. http://35.153.147.80:3000/api/attracion/100

image

### CODE REVIEW

**Comment by robinsonlin603** [comment]
image
想法是 num 為 可以做出頁面的最大值 ,這樣就不會限制住頁數

**Comment by cwpeng** [comment]
You cannot do this, as I emphasized before.
```
"SELECT `id` FROM `attractions`"
```
If you want to get count of rows in a table, you can use
```
SELECT count(*) FROM TABLE_NAME
```
It's best practice and optimized by MySQL.

**Comment by robinsonlin603** [comment]
修改成為
image

**Review by cwpeng — APPROVED** [review]
OK. Well Done.

**Comment by robinsonlin603** [comment]
thanks for your instruction

**Pull request merged**
