### PR TITLE
RWD測試版面

### PR DESCRIPTION
**Pull request by robinsonlin603**
老師好 我是林厚安 discord是Robinson＼(￣▽￣)／#1551
1.這是我的測試頁面 http://35.153.147.80:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
1. Your code will load the same page twice every time I scroll to the bottom.
2. Font size of 預定行程、登入註冊 is too small.
3. Search bar and 輕鬆享受台北一日遊 should align left with 台北一日遊 in desktop version. (width>1200px)
4. Color of attraction title, mrt and category should align with design in Figma.

Fix issues and leave comment for me to review again.

未命名-2

**Comment by robinsonlin603** [comment]
1.已經修改不會重複跑了
image
2.版面重新調整

**Comment by cwpeng** [comment]
1. Font size of 預定行程、登入註冊 is too small (should be 16px), not see the changes. (what you do makes no different)
2. As screenshot, search bar and 輕鬆享受台北一日遊 should align left with 台北一日遊 in desktop version. (width>1200px)
35 153 147 80_3000__asdsa

**Comment by cwpeng** [comment]
Layout is OK, but I cannot load more data when I scroll down to the bottom of page.

**Comment by robinsonlin603** [comment]
修改完成,麻煩在看過

**Comment by cwpeng** [comment]
Load data is OK. But mobile layout exceed screen width for now. Try to test carefully, because what you do may affect something you never expected.

未命名-4

**Pull request merged**
