### PR TITLE
景點資訊呈現

### PR DESCRIPTION
**Pull request by robinsonlin603**
老師好 我是林厚安 discord是Robinson＼(￣▽￣)／#1551
1.這是我的測試頁面 http://35.153.147.80:3000/
2. http://35.153.147.80:3000/attraction/10

### CODE REVIEW

**Comment by robinsonlin603** [comment]
1.修改mobile中的間距
image

2.修改 介紹與交通的line height:24px
image

**Comment by cwpeng** [comment]
What I see is around 80px space in your mobile layout:

35 153 147 80_3000_attraction_1(Samsung-Galaxy-S20-Ultra)

And I was wrong in the previous comment, the space between slider and navigator should be 40px, according to design.

**Comment by robinsonlin603** [comment]
1.已修改 減少原本的margin-top 部分
image

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
